llm_pool_info:
  - engine_name: "OpenAIInferenceEngine"
    model_name: "gpt-4o-mini"
    engine_arguments:
      api_key: "[YOUR OPENAI APIKEY]"

  - engine_name: "AnthropicInferenceEngine"
    model_name: "claude-3-haiku-20240307"
    engine_arguments:
      api_key: "[YOUR ANTHROPIC APIKEY]"

  - engine_name: "GoogleInferenceEngine"
    model_name: "gemini-1.0-pro-latest"
    engine_arguments:
      api_key: "[YOUR GOOGLE APIKEY]"
